/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Dark_Third.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { convertMaterialsToBasic } from "../../utils/convertToBasic";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/models/Light Room/Light_Third.glb");

  const newMaterials = convertMaterialsToBasic(materials);

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Floor_Vaccum_Third_Baked.geometry}
        material={newMaterials.Third_Real_Real_Texture_Set_Baked}
        position={[1.371, 0 - 0.02, -0.354]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={1.015}
      />
      <mesh
        geometry={nodes.Light_Third_Baked.geometry}
        material={newMaterials.REAL_third_Baked}
        position={[-0.819, 0.746 - 0.02, 1.115]}
        rotation={[Math.PI / 2, 0, 0.47]}
      />
      <mesh
        geometry={nodes.Fan_Third_Baked.geometry}
        material={newMaterials.Third_Real_Real_Texture_Set_Baked}
        position={[0.247, 0.951 - 0.02, 0.524]}
        rotation={[Math.PI / 2, 0, 0.47]}
      />
    </group>
  );
}
