/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Dark_Second.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { convertMaterialsToBasic } from "../../utils/convertToBasic";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/models/Light Room/Light_Second.glb");

  const newMaterials = convertMaterialsToBasic(materials);

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Light_Second_Baked.geometry}
        material={newMaterials.actual_second_bro_Baked}
        position={[0.053, 0 - 0.02, 0.341]}
        rotation={[Math.PI, 0, Math.PI]}
      />
    </group>
  );
}
